### ISSUE TITLE
Fix responsiveness

### ISSUE THREAD

**Issue by mikestone14** [paulnorthup/trees#11]
At the last breakpoint when the tree stage images all stack it looks like this

![screen shot 2014-11-19 at 8 30 54 pm](https://cloud.githubusercontent.com/assets/2905145/5118093/1a55b824-702b-11e4-8614-db8199431ed5.png)

Header also needs responsive work:
![screen shot 2014-11-19 at 8 36 10 pm](https://cloud.githubusercontent.com/assets/2905145/5118152/e8e732e4-702b-11e4-95a0-edbab6033ee3.png)

**Comment by paulnorthup** [comment]
mmm yea that's hot.
